name: NodeJs CI with npm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ContinuousIntegration:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencie npm
        run: npm i
      - run: npm run build --if-present
